version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - real_estate_finder
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - real_estate_finder_var:/var/www/symfony/var
            - real_estate_finder_vendor:/var/www/symfony/vendor
        networks:
            - real_estate_finder
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - real_estate_finder_var:/var/www/symfony/var
            - real_estate_finder_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - real_estate_finder
        env_file:
            - .env.nginx.local

volumes:
    real_estate_finder_var:
    real_estate_finder_vendor:
    db_app:

networks:
    real_estate_finder:
