version: "3"

services:
    mysql:
        container_name: mysql
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "mysql_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - real_estate_finder
    php:
        container_name: php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony
        networks:
            - real_estate_finder
        depends_on:
            - mysql
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony
        ports:
            - 80:80
        networks:
            - real_estate_finder
        env_file:
            - .env.nginx.local
        depends_on:
            - php
            - mysql

volumes:
    mysql_data:

networks:
    real_estate_finder:
